### ISSUE TITLE
Monitor C* clusters for out of band changes

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/reaper-operator#2]
The `Reaper` CRD allows you to specifies clusters as in the following example:

```yaml
apiVersion: reaper.cassandra-reaper.io/v1alpha1
kind: Reaper
metadata:
  name: cass-reaper
spec:
  image: jsanda/reaper-k8s:cfad3f9f4cac-e026be8176d4
  serverConfig:
    storageType: cassandra
    cassandraBackend:
      clusterName: cluster-1
      contactPoints:
      - cluster-1
      keyspace: reaper
      replication:
        networkTopologyStrategy:
          dc1: 3
  clusters:
  - name: cluster-2
    namespace: default
    service:
      name: cluster-2
      namespace: default
```

When this `Reaper` object is created, the operator will do the following:

* Create the `reaper` keyspace in the `cluster-1` cluster
* Create the Deployment for the Reaper application, which is named `cass-reaper`
* Make a REST API to add `cluster-2` to `cass-reaper`

A user can go into the Reaper UI and remove `cluster-2`. This would be an _out of band_ change with respect to the operator. It would make the actual state of `cass-reaper` different from the desired state , and the operator will not be aware of the change.

There needs to be a background job that checks for out of band changes. When the job detects an out of band change, it should queue the `Reaper` object for reconciliation. A subsequent reconciliation of `cass-reaper` for example, will result in `cluster-2` being added back to the Reaper application.

Note that the background monitoring job should only inspect clusters that are defined in `.spec.clusters`. Other clusters can be added to/removed from the Reaper application. The monitoring job will ignore them.

It is also important to note that clusters added to the Reaper application through `.spec.clusters` cannot  removed directly through the application. The clusters must be removed from `.spec.clusters` to trigger removal from the application.
