### ISSUE TITLE
Add support for JMX authentication

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/reaper-operator#4]
Reaper has the `jmxAuth` and `jmxCredentials` properties. This tickets aims to add support only for the latter. It offers more flexibility over `jmxAuth` since you can specify credentials for multiple clusters, e.g., 

```yaml
jmxCredentials:
  clusterProduction1:
    username: user1
    password: password1
  clusterProduction2:
    username: user2
    password: password2
```
